/**
 * ------------------------------------------------------------------
 * Arcade Frontend Architecture
 * Layer: Domains
 * Domain: Credentials
 *
 * The certificate as it looks, on screen: the same landscape A4 design the server prints to PDF
 * (backend `CertificateDocument`). It is printed on the shared certificate ground
 * (`/credentials/certificate-ground.svg`, generated by `scripts/build-certificate-ground.js`): a
 * layered paper-cut border around hatched security paper. Over it: the Arcade mark at the top left
 * (with the issuing organisation beside it, unless the issuer is the host institution) and the host
 * institution's lockup (`/credentials/host-lockup.svg`, from `scripts/build-host-lockup.js`) at the
 * top right; the text; and a QR code to the verification page. Pure and presentational; it states
 * nothing the record does not.
 *
 * Everything is placed in page millimetres (297 × 210) converted to container units, so the face
 * scales as one piece at any width — a thumbnail in a list or the hero of the public page. Keep the
 * positions in step with `CertificateDocument`.
 * ------------------------------------------------------------------
 */

import { useMemo, type CSSProperties, type ReactNode } from "react";
import { Cormorant_Garamond, EB_Garamond } from "next/font/google";
import QRCode from "qrcode";
import { ARCADE_WORDMARK_PATHS, ARCADE_WORDMARK_VIEWBOX } from "../lib/arcadeWordmark";
import type { IssuedCertificate } from "../types/credential.types";

const NAVY = "#1A2238";
const GOLD = "#B08D3C";
const MUTED = "#5B6475";


// The PDF's typefaces (backend Xhtml.DISPLAY and Xhtml.BOOK): Cormorant Garamond for the display
// lines, EB Garamond for running text. Loaded here so only pages showing a certificate fetch them.
const display = Cormorant_Garamond({ subsets: ["latin"], weight: ["500", "600"], style: ["normal", "italic"] });
const book = EB_Garamond({ subsets: ["latin"], weight: ["400", "600"] });

const mm = (v: number) => `${(v * 100) / 297}cqw`;
const pt = (v: number) => mm(v * 0.3528);

export interface CertificateFaceProps {
  certificate: Pick<
    IssuedCertificate,
    | "credentialCode"
    | "documentTitle"
    | "sourceLabel"
    | "title"
    | "recipientName"
    | "issuerName"
    | "issuerLogoUrl"
    | "issuedByHost"
    | "signatoryName"
    | "signatoryTitle"
    | "signatureUrl"
    | "conductedBy"
    | "scorePercent"
    | "achievedAt"
    | "issuedAt"
    | "expiresAt"
    | "revoked"
  >;
  /** The public verification page; printed as the QR code. Without it the code is left out. */
  verificationUrl?: string;
  className?: string;
}

function pct(v: number) {
  return `${Number(v.toFixed(2))}%`;
}

function longDate(iso: string) {
  return new Date(iso).toLocaleDateString("en-GB", { day: "numeric", month: "long", year: "numeric" });
}

/** A block placed on the page in millimetres. */
function At({ style, children }: { style: CSSProperties; children?: ReactNode }) {
  return <div style={{ position: "absolute", ...style }}>{children}</div>;
}

export function CertificateFace({ certificate: c, verificationUrl, className }: CertificateFaceProps) {
  const serif = "var(--font-serif, 'Noto Serif', Georgia, serif)";
  const field = (value: ReactNode, label: ReactNode) => (
    <>
      <div style={{ fontWeight: 600, fontSize: pt(13.5), lineHeight: 1.25 }}>{value}</div>
      <div style={{ marginTop: mm(0.8), fontSize: pt(10), color: MUTED }}>{label}</div>
    </>
  );
  const column = (left: number, width: number): CSSProperties => ({
    left: mm(left),
    width: mm(width),
    textAlign: "center",
    fontFamily: book.style.fontFamily,
  });

  return (
    <div
      className={className}
      style={{ containerType: "inline-size", width: "100%" }}
      role="img"
      aria-label={`${c.documentTitle}: ${c.title}, awarded to ${c.recipientName} by ${c.issuerName}${c.revoked ? " (revoked)" : ""}`}
    >
      <div
        className="relative w-full overflow-hidden"
        style={{
          aspectRatio: "297 / 210",
          color: NAVY,
          background: "#fff url(/credentials/certificate-ground.svg) center / 100% 100% no-repeat",
          lineHeight: 1.2,
        }}
      >
        {c.revoked && (
          <At style={{ inset: 0, display: "flex", alignItems: "center", justifyContent: "center", pointerEvents: "none" }}>
            <span
              aria-hidden
              className="select-none font-bold"
              style={{ fontSize: pt(96), color: "#E9B9B1", transform: "rotate(-20deg)" }}
            >
              REVOKED
            </span>
          </At>
        )}

        <At style={{ left: mm(28), top: mm(24), display: "flex", alignItems: "center", gap: mm(5) }}>
          <svg
            viewBox={`0 0 ${ARCADE_WORDMARK_VIEWBOX.width} ${ARCADE_WORDMARK_VIEWBOX.height}`}
            style={{ width: mm(34), height: mm(7.5) }}
            aria-hidden
          >
            {ARCADE_WORDMARK_PATHS.map((d, i) => (
              <path key={i} d={d} fill={NAVY} />
            ))}
          </svg>
          {/* The host's lockup is always at the right; another issuer is named here. */}
          {!c.issuedByHost && (
            <>
              <span style={{ width: mm(0.3), height: mm(10), background: GOLD }} />
              {c.issuerLogoUrl ? (
                // eslint-disable-next-line @next/next/no-img-element
                <img src={c.issuerLogoUrl} alt="" style={{ maxHeight: mm(11), maxWidth: mm(44) }} className="object-contain" />
              ) : (
                <span>
                  <span className="block font-bold" style={{ fontFamily: serif, fontSize: pt(13), lineHeight: 1.1 }}>
                    {c.issuerName}
                  </span>
                  <span className="block" style={{ fontSize: pt(8), letterSpacing: pt(1.2), color: MUTED }}>
                    ISSUING ORGANISATION
                  </span>
                </span>
              )}
            </>
          )}
        </At>

        {/* The host lockup is 3.194 : 1 (see scripts/build-host-lockup.js). */}
        <At style={{ right: mm(27), top: mm(19.5) }}>
          {/* eslint-disable-next-line @next/next/no-img-element */}
          <img src="/credentials/host-lockup.svg" alt="" style={{ display: "block", width: mm(54.3), height: mm(17) }} />
        </At>

        {/* Everything below the header is centred on the page's axis (x = 148.5 mm), as in the PDF. */}
        <At style={{ left: mm(28), top: mm(56), width: mm(241), textAlign: "center", fontFamily: display.style.fontFamily, fontWeight: 500, fontSize: pt(44), lineHeight: 1.05 }}>
          {c.documentTitle}
        </At>
        {/* The award reads as one block: each line follows the last, with margins tuned (as in the
            PDF, but measured in the browser, whose font metrics differ slightly) so the gaps between the
            inked text are equal: 6 mm. */}
        <At style={{ left: mm(28), top: mm(84), width: mm(241), textAlign: "center" }}>
          <div style={{ fontFamily: display.style.fontFamily, fontStyle: "italic", fontWeight: 500, fontSize: pt(15), lineHeight: 1, color: MUTED }}>
            This is to certify that
          </div>
          <div style={{ marginTop: mm(5.6), fontFamily: display.style.fontFamily, fontWeight: 600, fontSize: pt(34), lineHeight: 1 }}>
            {c.recipientName}
          </div>
          <div style={{ marginTop: mm(3.6), fontFamily: display.style.fontFamily, fontStyle: "italic", fontWeight: 500, fontSize: pt(15), lineHeight: 1, color: MUTED }}>
            has successfully passed the {c.sourceLabel.toLowerCase()}
          </div>
          <div style={{ marginTop: mm(5.2), fontFamily: book.style.fontFamily, fontWeight: 600, fontSize: pt(16), lineHeight: 1.2 }}>
            {c.title}
          </div>
          <div style={{ marginTop: mm(3.3), fontFamily: book.style.fontFamily, fontSize: pt(13), lineHeight: 1.4 }}>
            conducted by {c.conductedBy || c.issuerName}
            {c.scorePercent != null && (
              <>
                , securing a score of <b style={{ fontWeight: 600 }}>{pct(c.scorePercent)}</b>
              </>
            )}
            .
          </div>
        </At>

        {/* Three centred columns — date, signature, issuer. The signature column starts higher by
            the height of its image and rule, so all three share the same text lines. */}
        <At style={{ ...column(43, 62), top: mm(163) }}>{field(longDate(c.achievedAt), "Date of award")}</At>
        {c.signatoryName && c.signatureUrl && (
          <At style={{ ...column(117.5, 62), top: mm(147) }}>
            <div style={{ height: mm(15), display: "flex", alignItems: "flex-end", justifyContent: "center" }}>
              {/* eslint-disable-next-line @next/next/no-img-element */}
              <img src={c.signatureUrl} alt="" style={{ maxHeight: mm(15), maxWidth: mm(56) }} className="object-contain" />
            </div>
            <div style={{ width: mm(56), height: mm(0.25), margin: `${mm(0.3)} auto ${mm(0.7)}`, background: NAVY }} />
            {field(c.signatoryName, c.signatoryTitle)}
          </At>
        )}
        <At style={{ ...column(183, 80), top: mm(163) }}>{field(c.issuerName, "Issuing organisation")}</At>

        {verificationUrl && (
          <At style={{ left: mm(22), top: mm(160), width: mm(20), textAlign: "center" }}>
            <QrMark value={verificationUrl} />
            <div className="font-bold" style={{ fontSize: pt(5.5), letterSpacing: pt(0.6), marginTop: mm(1.2) }}>
              SCAN TO VERIFY
            </div>
          </At>
        )}

        <At style={{ left: mm(58.5), top: mm(178), width: mm(180), textAlign: "center", fontFamily: book.style.fontFamily, fontSize: pt(11.5) }}>
          {c.expiresAt ? `This certificate is valid until ${longDate(c.expiresAt)}` : "This certificate does not expire."}
        </At>
        <At style={{ left: mm(58.5), top: mm(184.5), width: mm(180), textAlign: "center", fontSize: pt(6.8), lineHeight: 1.45, color: MUTED }}>
          Credential ID <b>{c.credentialCode}</b> · Issued {longDate(c.issuedAt)}
          <br />
          {verificationUrl && <>Verify at {verificationUrl} · </>}Any alteration of this document invalidates it.
        </At>
      </div>
    </div>
  );
}

/** The verification QR code as crisp SVG modules. */
function QrMark({ value }: { value: string }) {
  const { size, d } = useMemo(() => {
    const qr = QRCode.create(value, { errorCorrectionLevel: "M" });
    const n = qr.modules.size;
    let path = "";
    for (let y = 0; y < n; y++) {
      for (let x = 0; x < n; x++) {
        if (qr.modules.get(x, y)) path += `M${x} ${y}h1v1h-1z`;
      }
    }
    return { size: n, d: path };
  }, [value]);

  return (
    <svg
      viewBox={`0 0 ${size} ${size}`}
      style={{ display: "block", width: mm(18), height: mm(18), margin: "0 auto" }}
      shapeRendering="crispEdges"
      aria-hidden
    >
      <path d={d} fill={NAVY} />
    </svg>
  );
}
