import type { IssuedBadge } from '@/domains/credentials';
import type { ProfileCertificate } from '../types/profile.types';

export const DEMO_BADGES: IssuedBadge[] = [
  {
    credentialCode: 'ARC-BADGE-TS-9801',
    name: 'Advanced TypeScript Architect',
    criteria: 'Completed Advanced TypeScript mastery curriculum & checkpoint exams with 95%+ score.',
    contentType: 'COURSE',
    contentId: 'course-typescript-adv',
    contentPath: '/courses/advanced-typescript',
    recipientName: 'Abel Anil Mathew',
    recipientHandle: 'abel',
    issuerName: 'Arcade Academy',
    issuerHandle: 'arcade',
    issuerLogoUrl: null,
    issuedAt: '2026-02-15T10:00:00Z',
    publicVisible: true,
    revoked: false,
    revokedAt: null,
    revokedReason: null,
    badgeClass: {
      code: 'ARC-COURSE-L3',
      name: 'Advanced Course Badge',
      family: {
        key: 'COURSE',
        label: 'Course Excellence',
        contentType: 'COURSE',
        criteria: 'Course completion & checkpoint mastery',
      },
      tier: {
        level: 3,
        key: 'LEVEL_3',
        name: 'Advanced',
        label: 'Level 3 · Advanced',
        meaning: 'Mastery of advanced distributed architecture & languages',
        guidance: 'Awarded for completing level 3 advanced curriculum',
      },
    },
  },
  {
    credentialCode: 'ARC-BADGE-FS-5512',
    name: 'Full-Stack System Specialist',
    criteria: 'Completed comprehensive full-stack interactive workshops and live hackathons.',
    contentType: 'EVENT',
    contentId: 'ws-fullstack-systems',
    contentPath: '/events/fullstack-systems',
    recipientName: 'Abel Anil Mathew',
    recipientHandle: 'abel',
    issuerName: 'Arcade Academy',
    issuerHandle: 'arcade',
    issuerLogoUrl: null,
    issuedAt: '2026-03-01T14:30:00Z',
    publicVisible: true,
    revoked: false,
    revokedAt: null,
    revokedReason: null,
    badgeClass: {
      code: 'ARC-EVENT-L2',
      name: 'Intermediate Event Badge',
      family: {
        key: 'EVENT',
        label: 'Event & Workshop Specialist',
        contentType: 'EVENT',
        criteria: 'Hands-on live laboratory & event completion',
      },
      tier: {
        level: 2,
        key: 'LEVEL_2',
        name: 'Intermediate',
        label: 'Level 2 · Intermediate',
        meaning: 'Demonstrated intermediate proficiency in event sessions',
        guidance: 'Awarded for completing interactive technical events & workshops',
      },
    },
  },
  {
    credentialCode: 'ARC-BADGE-EXAM-3309',
    name: 'Cloud Native & Microservices Ace',
    criteria: 'Achieved top percentile in Cloud Native Architecture & Distributed Systems Proctored Exam.',
    contentType: 'EXAM',
    contentId: 'exam-cloud-native',
    contentPath: '/exams/cloud-native',
    recipientName: 'Abel Anil Mathew',
    recipientHandle: 'abel',
    issuerName: 'Cloud Standards Guild',
    issuerHandle: 'cloudguild',
    issuerLogoUrl: null,
    issuedAt: '2026-03-20T09:15:00Z',
    publicVisible: true,
    revoked: false,
    revokedAt: null,
    revokedReason: null,
    badgeClass: {
      code: 'ARC-EXAM-L3',
      name: 'Mastery Exam Badge',
      family: {
        key: 'EXAM',
        label: 'Exam Distinction',
        contentType: 'EXAM',
        criteria: 'Proctored technical certification exam mastery',
      },
      tier: {
        level: 3,
        key: 'LEVEL_3',
        name: 'Advanced',
        label: 'Level 3 · Advanced',
        meaning: 'Demonstrated advanced mastery in proctored exam',
        guidance: 'Awarded for highest distinction in proctored exams',
      },
    },
  },
  {
    credentialCode: 'ARC-BADGE-EVENT-1092',
    name: 'Global Hackathon Finalist',
    criteria: 'Built high-impact production microservice prototype during Arcade 2026 Hackathon.',
    contentType: 'EVENT',
    contentId: 'event-hackathon-2026',
    contentPath: '/events/hackathon-2026',
    recipientName: 'Abel Anil Mathew',
    recipientHandle: 'abel',
    issuerName: 'Arcade Global',
    issuerHandle: 'arcade',
    issuerLogoUrl: null,
    issuedAt: '2026-03-28T18:00:00Z',
    publicVisible: true,
    revoked: false,
    revokedAt: null,
    revokedReason: null,
    badgeClass: {
      code: 'ARC-EVENT-L1',
      name: 'Foundation Event Badge',
      family: {
        key: 'EVENT',
        label: 'Event & Community',
        contentType: 'EVENT',
        criteria: 'Active event participation and verified project submission',
      },
      tier: {
        level: 1,
        key: 'LEVEL_1',
        name: 'Foundation',
        label: 'Level 1 · Foundation',
        meaning: 'Active event participation and verified submission',
        guidance: 'Awarded for official event participation',
      },
    },
  },
];

export const DEMO_CERTIFICATES: ProfileCertificate[] = [
  {
    name: 'Certified Professional Full-Stack Developer',
    issuer: 'Arcade Certification Board',
    date: 'Feb 2026',
    idCode: 'ARC-CERT-2026-8841',
  },
  {
    name: 'Distributed Systems & Microservices Engineering',
    issuer: 'Arcade Institute of Tech',
    date: 'Jan 2026',
    idCode: 'ARC-CERT-2026-3192',
  },
  {
    name: 'Next.js & Modern React Architecture',
    issuer: 'Frontend Masters Guild',
    date: 'Dec 2025',
    idCode: 'ARC-CERT-2025-9012',
  },
  {
    name: 'PostgreSQL Database Administration & Tuning',
    issuer: 'Open Database Standards',
    date: 'Nov 2025',
    idCode: 'ARC-CERT-2025-4421',
  },
];
